### ISSUE TITLE
Additional LiveU monitoring options

### ISSUE THREAD

**Issue by reedog117** [715209/liveu-stats-bot#2]
Can you add additional commands for checking LiveU battery state and temperature? Would be very cool to get automated alerts when the unit is low on battery or the unit is in danger of overheating.

**Comment by 715209** [comment]
Hey Reedog,

I have been working on this in the new version (the nodejs version is not maintained anymore)
You can find the new version here: https://github.com/715209/liveu_stats_bot/pull/1

**Comment by MrHamel** [comment]
When will that pull request be merged? Thanks!

**Comment by 715209** [comment]
@MrHamel has been merged :+1:
